# Generated by Django 5.2.6 on 2025-11-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_autor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem de Destaque do Produto', upload_to='produtos_img/'),
        ),
    ]
